# Generated by Django 4.2.2 on 2023-07-13 11:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68c9e323-024a-489e-a8e0-c02ac77e48c1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='VendingMachineSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2e4473d5-8ff6-444d-8a41-8732d423390b'), editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('row', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('column', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vending.product')),
            ],
            options={
                'db_table': 'vending_machine_slot',
            },
        ),
    ]
