# Generated by Django 4.2.2 on 2023-07-13 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0002_alter_product_id_vendingmachineslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('57a9c4fe-9680-4b64-bf09-2db618c352ad'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendingmachineslot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2ba160c9-59a3-48d1-9c04-21877db47280'), editable=False, primary_key=True, serialize=False),
        ),
    ]
