# Generated by Django 4.2.2 on 2023-07-13 13:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0003_product_updated_at_alter_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(default=uuid.UUID('449f7182-beec-4c3d-bb67-8e5bc48a6d30'), editable=False, max_length=200, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1487777e-413a-4890-a2c2-e70e943ce6d2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendingmachineslot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cb20042c-a26a-4f78-95ed-00532ac950a9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
