# Generated by Django 4.2.2 on 2023-07-13 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0004_user_product_description_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d73a7ca6-74c5-42df-9137-b36b86101c1a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(editable=False, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendingmachineslot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a2a1f5e3-cb7d-4f67-92a3-1191c539dd2a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
