# Generated by Django 4.2.2 on 2023-07-14 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0005_alter_product_id_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('21638876-6233-44c5-9583-6a459fbc359e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendingmachineslot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c6197637-004e-472b-b90b-0b2efebc6833'), editable=False, primary_key=True, serialize=False),
        ),
    ]
