# Generated by Django 4.2.2 on 2023-07-14 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0006_alter_product_description_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('afbe132b-2c98-49e5-89e3-7dd771507d71'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendingmachineslot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('47021fe9-69d0-405e-9165-656178045cea'), editable=False, primary_key=True, serialize=False),
        ),
    ]
