# Generated by Django 4.2.2 on 2023-07-14 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0008_alter_product_description_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('64035fbc-68b1-4f3b-a609-68d2b134102a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendingmachineslot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4276b876-7d01-45ed-a988-6728bcfe9d7a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
