# Generated by Django 4.2.2 on 2023-07-14 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0009_alter_product_description_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('42180c93-1807-46aa-b65c-0c9e4af4645f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendingmachineslot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1dec7bf6-c0e9-4de3-8e94-3a868f7f3c96'), editable=False, primary_key=True, serialize=False),
        ),
    ]
