# Generated by Django 4.2.2 on 2023-07-17 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0010_alter_product_description_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e3484878-1e7e-45dd-8cda-6a4002afdfc3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('916e307d-0138-4e6b-92de-aaf76e4e81e0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vendingmachineslot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6948cd41-a272-4bd7-b96b-68219eb8a5eb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
