# Generated by Django 4.2.2 on 2023-07-19 08:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0011_user_id_alter_product_id_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dcab55ed-48ed-4e4e-b712-b9eba1db2c61'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0c5ae958-8174-4ebe-979e-847aa899a03e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendingmachineslot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7c07654b-97fa-4fb4-9ccb-99a70bba9836'), editable=False, primary_key=True, serialize=False),
        ),
    ]
