# Generated by Django 4.2.2 on 2023-07-19 08:50

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0012_alter_product_id_alter_user_balance_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d3e06fdf-ae0f-4268-b3cf-168de9574020'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('feed93ba-39fe-4415-a2c6-11125be52ef0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendingmachineslot',
            name='column',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vendingmachineslot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4dd13214-76ef-423b-bb8c-f98cb509edbf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
